name: feeling-finder
grade: stable
version: 1.6.2
adopt-info: appinfo
base: core24
confinement: strict
compression: lzo
platforms:
  amd64:

apps:
  feeling-finder:
    command: feeling_finder
    extensions: [gnome]
    common-id: codes.merritt.FeelingFinder
    desktop: utils/codes.merritt.FeelingFinder.desktop
    plugs:
      - network
      - network-status
      - network-bind
      - unity7

parts:
  feeling-finder:
    plugin: dump
    source: https://github.com/Merrit/feeling_finder/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/FeelingFinder-Linux-Portable.tar.gz
    prime:
      - -PORTABLE
      - -README.md

  appinfo:
    plugin: dump
    after: [feeling-finder]
    source: https://github.com/Merrit/feeling_finder.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    parse-info: [packaging/linux/codes.merritt.FeelingFinder.metainfo.xml]
    override-pull: |
      craftctl default
      sed -e 's|Icon=codes.merritt.FeelingFinder|Icon=${SNAP}/utils/codes.merritt.FeelingFinder.svg|' -i packaging/linux/codes.merritt.FeelingFinder.desktop
      mkdir utils
      cp packaging/linux/codes.merritt.FeelingFinder.desktop utils
      cp assets/icons/codes.merritt.FeelingFinder.svg utils
    prime:
      - utils

  deps:
    after: [appinfo]
    plugin: nil
    stage-packages:
      - libkeybinder-3.0-0
      - libappindicator3-1
    prime:
      - usr/lib/*/libappindicator*
      - usr/lib/*/libkeybinder*
